export const actionType = {
  GET_RECIPE: "GET_RECIPE",
  GET_USER: "GET_USER",
  ADD_SAVE: "ADD_SAVE",
  ADD_COUNT_ONE: "ADD_COUNT_ONE",
  ADD_COUNT_TWE: "ADD_COUNT_TWE",
  OPEN_CLOSE_MODAL:"OPEN_CLOSE_MODAL"
};
